#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################

BASHLETS_WEB_API_AMAZON_ENDPOINT="${BASHLETS_WEB_API_AMAZON_ENDPOINT:-https://www.amazon.com/s/ref=nb_ss?field-keywords=}"
BASHLETS_WEB_API_BING_ENDPOINT="${BASHLETS_WEB_API_BING_ENDPOINT:-https://www.bing.com/search?q=}"
BASHLETS_WEB_API_CHOOSEALICENSE_ENDPOINT="${BASHLETS_WEB_API_CHOOSEALICENSE_ENDPOINT:-https://choosealicense.com/licenses/}"
BASHLETS_WEB_API_DYNDNS_ENDPOINT="${BASHLETS_WEB_API_DYNDNS_ENDPOINT:-http://checkip.dyndns.org/}"
BASHLETS_WEB_API_GOOGLE_ENDPOINT="${BASHLETS_WEB_API_GOOGLE_ENDPOINT:-https://www.google.com/search?hl=\${lang}#q=}"
BASHLETS_WEB_API_IPAPI_ENDPOINT="${BASHLETS_WEB_API_IPAPI_ENDPOINT:-https://ipapi.co}"
BASHLETS_WEB_API_ISUP_ENDPOINT="${BASHLETS_WEB_API_ISUP_ENDPOINT:-https://isitup.org}"
BASHLETS_WEB_API_MANKIER_ENDPOINT="${BASHLETS_WEB_API_MANKIER_ENDPOINT:-https://www.mankier.com/api/explain/?cols=\${cols}\&q=}"
BASHLETS_WEB_API_OEIS_ENDPOINT="${BASHLETS_WEB_API_OEIS_ENDPOINT:-https://oeis.org}"
BASHLETS_WEB_API_REDDIT_ENDPOINT="${BASHLETS_WEB_API_REDDIT_ENDPOINT:-https://www.reddit.com/}"
BASHLETS_WEB_API_WHATTHECOMMIT_ENDPOINT="${BASHLETS_WEB_API_WHATTHECOMMIT_ENDPOINT:-https://whatthecommit.com/index.txt}"
BASHLETS_WEB_API_WIKIPEDIA_ENDPOINT="${BASHLETS_WEB_API_WIKIPEDIA_ENDPOINT:-https://\${lang}.wikipedia.org/w/index.php?search=}"
BASHLETS_WEB_API_YAHOO_ENDPOINT="${BASHLETS_WEB_API_YAHOO_ENDPOINT:-https://search.yahoo.com/search?p=}"

# text/json
BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT="${BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT:-text}"

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
