#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# cf. http://stackoverflow.com/questions/5991756/
# TODO parse internal output format!

source bashlets web::api::defs

#@public
function bashlets::web::api::oeis::validate_sequence_id()
{
    declare -u sequence_id="$1"
    [[ $sequence_id =~ ^A[0-9]{6}$ ]]
}

function __bashlets::web::api::oeis::get_name()
{
    while read line
    do
        [[ $line =~ ^%N[[:space:]]A[0-9]{6}[[:space:]](.*) ]]  \
            && echo "${BASH_REMATCH[1]}"
    done
}

#@public
function bashlets::web::api::oeis::get_sequence_by_id()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers
    local query

    bashlets::web::api::oeis::validate_sequence_id "$sequence_id"

    query="search?q=id:$sequence_id&fmt=$BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT"
    curl -s "$BASHLETS_WEB_API_OEIS_ENDPOINT/$query"
}

#@public
function bashlets::web::api::oeis::describe_sequence_by_id()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers

    (
        # we need to use the internal format
        BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT=text

        bashlets::web::api::oeis::get_sequence_by_id "$sequence_id"  \
            | __bashlets::web::api::oeis::get_name
    )
}

#@public
function bashlets::web::api::oeis::get_sequences_by_points()
{
    local points="$@"
    local query

    # cf. http://stackoverflow.com/questions/1527049/
    function join_by() { local IFS="$1"; shift; echo "$*"; }

    query="search?q=$(join_by , $@)&fmt=$BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT"
    curl -s "$BASHLETS_WEB_API_OEIS_ENDPOINT/$query"

    unset join_by
}

#@public
function bashlets::web::api::oeis::describe_sequences_by_points()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers

    (
        # we need to use the internal format
        BASHLETS_WEB_API_OEIS_PREFERRED_FORMAT=text

        bashlets::web::api::oeis::get_sequences_by_points "$@"  \
            | __bashlets::web::api::oeis::get_name
    )
}

# grabs the images used to graph the data points

#@public
function bashlets::web::api::oeis::get_graph()
{
    # WARNING: output is in PNG format

    declare -u sequence_id="${1:-A000040}"  # the prime numbers
    local query

    bashlets::web::api::oeis::validate_sequence_id "$sequence_id"

    query="$sequence_id/graph?png=1"
    curl -s "$BASHLETS_WEB_API_OEIS_ENDPOINT/$query"
}

#@public
function bashlets::web::api::oeis::get_recent()
{
    curl -s "$BASHLETS_WEB_API_OEIS_ENDPOINT/recent.txt" | gunzip -
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
